// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/currency/add": {
            "post": {
                "description": "Add cryptocurrency",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cryptocurrency"
                ],
                "summary": "Add cryptocurrency",
                "operationId": "AddCryptocurrency",
                "parameters": [
                    {
                        "description": "Cryptocurrency add data",
                        "name": "cryptocurrency",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.AddCryptocurrencyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/currency/price": {
            "post": {
                "description": "Get pice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cryptocurrency"
                ],
                "summary": "Get price",
                "operationId": "GetPriceCryptocurrency",
                "parameters": [
                    {
                        "description": "Get price data",
                        "name": "price",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.PriceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PriceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/currency/remove": {
            "post": {
                "description": "Remove cryptocurrency",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cryptocurrency"
                ],
                "summary": "Remove cryptocurrency",
                "operationId": "RemoveCryptocurrency",
                "parameters": [
                    {
                        "description": "Cryptocurrency remove data",
                        "name": "cryptocurrency",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.RemoveCryptocurrencyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddCryptocurrencyRequest": {
            "type": "object",
            "required": [
                "symbol"
            ],
            "properties": {
                "symbol": {
                    "type": "string",
                    "example": "BTC"
                }
            }
        },
        "dto.PriceRequest": {
            "type": "object",
            "required": [
                "symbol",
                "timestamp"
            ],
            "properties": {
                "symbol": {
                    "type": "string",
                    "example": "BTC"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1754578944
                }
            }
        },
        "dto.PriceResponse": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "dto.RemoveCryptocurrencyRequest": {
            "type": "object",
            "required": [
                "symbol"
            ],
            "properties": {
                "symbol": {
                    "type": "string",
                    "example": "BTC"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AFFARM",
	Description:      "RestAPI for AFFARM",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
